run:
  timeout: 5m

linters:
  disable-all: false
  enable:
    - funlen
    - dogsled
    - dupl
    # - lll
    - whitespace
    - wsl
    - exportloopref
  disable:
    - scopelint
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - unparam
  presets:
    - bugs
    - unused
    # - style
  fast: false
