run:
  timeout: 5m
  tests: false
  skip-files:
    - 'internal/config/http_config.go'
    - 'internal/config/config.go'
linters:
   enable-all: true
   disable:
     - cyclop
     - depguard
     - exhaustivestruct
     - exhaustruct
     - forbidigo
     - gci
     - gochecknoglobals
     - gochecknoinits
     - godox
     - goerr113
     - gofumpt
     - gomnd
     - mnd
     - lll
     - musttag
     - nakedret
     - nlreturn
     - nolintlint
     - nonamedreturns
     - tagliatelle
     - varnamelen
     - wrapcheck
linters-settings:
   estif:
     min-complexity: 4
   maligned:
     suggest-new: true
