# See documentation at https://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - >-
        -s -w -X main.version={{.Version}}
        -X main.commit={{.Commit}}
        -X main.date={{.CommitDate}}
release:
  draft: true
  github:
    owner: NETWAYS
    name: check_logstash
archives:
  - format: binary
    name_template: >-
      {{- if eq .Arch "amd64" }}x86_64{{ end }}
      {{- if eq .Os "linux" }}Linux{{ end }}
      {{- if eq .Os "windows" }}Windows{{ end }}
      {{- if eq .Os "darwin" }}Darwin{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT-{{.ShortCommit}}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
