name: Question
description: Ask a question
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: description
    attributes:
      label: Ask a question
      description: Please provide as much context as possible. You can use markdown.
