---
name: Acceptance Tests
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        logstashversion: [5, 6, 7]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gpg curl
          wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
          echo "deb https://artifacts.elastic.co/packages/${{ matrix.logstashversion }}.x/apt stable main" | sudo tee /etc/apt/sources.list.d/elastic.list
          sudo apt-get update
          sudo apt-get install logstash
          mkdir -p /tmp/logstash/data /tmp/logstash/logs
          sudo bash -c 'echo "http.host: 127.0.0.1" >> /etc/logstash/logstash.yml'
          sudo bash -c 'echo "http.port: 9600-9700" >> /etc/logstash/logstash.yml'

      - name: Test with Logstash
        run: |
          if [ "${{ matrix.logstashversion }}" -gt "6" ]; then unset JAVA_HOME; fi 
          /usr/share/logstash/bin/logstash  --path.settings /etc/logstash/ --path.data /tmp/logstash/data --path.logs /tmp/logstash/logs -e 'input { tcp { port => 5044 }}' &
          while ! echo exit | curl http://localhost:9600; do sleep 10; done
          ./check_logstash -H localhost
