---
name: Rake Tests
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
  steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run rake
        run: |
          rake
